import Head from 'next/head'
import { Tstar, Trebuc } from '@/components/Base/Fonts/Fonts'

export default function Home() {
  return (
    <>
      <Head>
        <title>Daya Dimensi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${Tstar.className} ${Trebuc.className}`}>
        <h1>FRONTEND DEVELOPER TEST</h1>
      </main>
    </>
  )
}
